### ISSUE TITLE
Issue with notFound never triggered

### ISSUE THREAD

**Issue by Nyholm** [krasimir/navigo#82] opened 2017-03-08 09:14 UTC
I have a simple route like: 

```js
router
  .on({
    '/product/:id': function (params) {
      renderProduct(params.id)
    },
    '/':function() {
      renderStartpage();
    }
  })
  .notFound(function() {
    pageNotFoundController();
  });
```

If the URL is `/` it will go to start page. Also if the URL is `/foobar`. I can never seem to be triggering the `pageNotFoundController()`. 

How should I configure my routes differently? Naturally I only want to valid routes: `/` and `/product/XX`.

**Comment by nordskill** [comment] 2017-03-14 21:24
I have exactly the same problem: **root** handler doesn't work with **notFound** handler.

**Comment by nordskill** [comment] 2017-03-15 09:08
I guess I've found a workaround for this issue:

`router.on(function () {
    if (window.location.pathname.length > 1) {
     console.log('404');
    } else {
     console.log('home');
    }
  }).resolve();`

**Comment by krasimir** [comment] 2017-03-15 14:19
@Nyholm @nordskill just released `4.2.0`. In [here](https://github.com/krasimir/navigo/commit/4411cb71ff5fe819d5f5ba3f834dd07639ec2dec) you'll find a test that is replicating your issue. Can you please use the new version and let me know if it works.

**Comment by nordskill** [comment] 2017-03-16 10:12
Hello, Krasimir
It seems still not to be working for me.

**Comment by krasimir** [comment] 2017-03-16 20:34
@nordskill can you please post your route definitions.

**Comment by nordskill** [comment] 2017-03-17 11:36
I'm actually trying the refined version of your demo: [JS](http://nordskill.com/dock/navigo/scripts.js)
The actual page (without content, but buttons are clickable): [](http://nordskill.com/dock/navigo)

**Comment by johnhult** [comment] 2017-03-21 20:28
I'm having the same problem. My routing looks like


	
	var rootUrl = '';
	var useHash = false;
	var router = new Navigo(rootUrl, useHash);

	router.on({
		'/': function() {
			console.log('/ (home)');
			mainNavigation('home');
			setTimeout(function() {
				runHome();
			}, 600);
		},
		'/bio': function() {
			console.log('bio');
			openOverlay('');
			runBio();
		},
		'/work': function() {
			console.log('work');
			mainNavigation('work');
			setTimeout(function() {
				runWork();
			}, 600);
		},
		'/blog': function() {
			console.log('blog');
			mainNavigation('blog');
			setTimeout(function() {
				runBlog();
			}, 600);
		}
	})
	.notFound(function() {
		console.log('page not found');
	})
	.resolve();

**Comment by krasimir** [comment] 2017-03-25 06:21
@nordskill sorry, I think I didn't make this clear and it looks like I deleted `gh-pages` branch only locally. The Navigo file that you are using is an old one and does not have the `notFound` method. You are getting that in the console:
![image](https://cloud.githubusercontent.com/assets/528677/24319976/f30ee78e-1133-11e7-9a94-4c129fef0b15.png)
Please use the latest version from https://github.com/krasimir/navigo/tree/master/lib or npm.

**Comment by krasimir** [comment] 2017-03-25 06:23
@johnhult can you please make sure that you are using the latest version. Also something really important ⚠️ - the order of how you add the routes matter. So make sure that you put the `/` at the end of your `on` call.

**Comment by johnhult** [comment] 2017-03-30 14:51
@krasimir I changed the position of the `/` to the end instead but nothing really changed. Said two different things in the README.md, so I thought it didn't matter :) I have the latest npm version of navigo so that should be okay.

What happens is that if I go to `/asdf` (i.e. a non-existing route) it will just load the `/asdf` route as the root route instead. If I then try to navigate to for example `/work`, it will instead go to `/asdf/work`.

I was wondering if it could have something to do with my gulptask if it isn't Navigo itself?

```
	gulp.task('express', function() {
		var express = require('express');
		app = express();
		app.use(historyApiFallback());
		app.use(require('connect-livereload')({port: 4001}));
		app.use(express.static(__dirname));
		app.listen(4000);
	});
```

**Comment by krasimir** [comment] 2017-04-01 14:01
@johnhult that `historyApiFallback` may be in a conflict with Navigo. We've made a couple of releases last week that may address those issues. Can you please download the latest version and let me know a URL (if possible) to reproduce the problem one more time.

**Comment by krasimir** [comment] 2017-05-28 13:54
Closing this one. Let me know guys if you still experience similar issues and will reopen.

**Closed by krasimir** 2017-05-28 13:54 UTC

**Comment by andrewheekin** [comment] 2017-06-12 16:08
getting the same issue as @johnhult from Mar 30. When I manually enter an non-existent route `/asdf`, it renders the content from the default route `/` but leaves the incorrect route `/asdf` in the url and builds on it in subsequent requests (`/asdf/projects`). I'm using `webpack-dev-server` and `historyApiFallback`, project here: https://github.com/andrewheekin/andrewdotcom-es6, all routing is in `js/router.js`

**Comment by wishnevski** [comment] 2018-11-13 20:36
I am using navigo on NodeJS and all of my requests redirected on default path ('*' or '/'). In HTTP Request Handler Function i am calling `router.navigate(path).resolve()`. If i calling `navigate(path)` without `resolve()` - router ignored. How to solve this problem?
