### ISSUE TITLE
Going directly into a route via browser does not work

### ISSUE THREAD

**Issue by FaBeyyy** [krasimir/navigo#230] opened 2018-12-21 13:27 UTC
```js
this.router
            .on({
                '/partner/:partnerId': (params, queryParams) => new PartnerView(hc, params, queryParams)
            })
            .notFound(function (query) {
                console.log('404');
            }) 
            .resolve();
```

for example going into localhost:port/partner/123 works when being redirected with data-navigo or the navigo navigate function.
Entering it directly into the browser does not work when using non hash routing, it simply fallsback to the default route (or notFound but that doesnt work either see #229 ).

**Comment by jordanaustin** [comment] 2018-12-27 16:50
I had a similar problem, but it wasn't due to Navigo, but rather the local web server I was running. I don't know if this is the same issue for you, but I'll put it here, just in case. I had to add a `<base href="/" />` into my index.html (or default page) to get it to work correctly when dealing with paths that were multi-levels deep (e.g. /users/123).

**Comment by VladimirDev93** [comment] 2019-01-02 19:34
I had this problem and then I found out that it's not Navigo, but something else. The problem is that your routes are not configured on the server. If you want to show some content by directly going to a particular route, you server needs to know what files to serve when you or the client navigates to the route. The reason why you are only able to see content on particular route with a hash is because hash means "history" therefore, when you navigate to the specific route (from home page) and you reload the page with a particular route is because you are seeing content from your **local history**. More info: https://github.com/krasimir/navigo/issues/207#issuecomment-413566036

**Comment by cferdinandi** [comment] 2020-05-12 16:46
You will need to configure your web server to point to your `index.html` page regardless of the URL path.

If you're using Apache, you might do something like this:

```apache
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^index\.php$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.html [L]
</IfModule>
```

In Node.js, you might do something like this.

```js
onst path = require("path")
const express = require("express")
const app = new express()

// requests for static files in the "public" directory
// like JavaScript, CSS, images will be served
app.use(express.static("public"))

// Every other request will send the index.html file that
// contains your application
app.use("*", function(req, resp) {
  resp.sendFile("/public/index.html")
})

app.listen("8000")
```

**Comment by JulioPradera** [comment] 2020-12-08 01:24
@cferdinandi I configured Apache as you said, but the only difference is that, when trying to access a route via URL, instead of showing error 404, error 503 now appears. But everything else continues to function normally.

**Comment by krasimir** [comment] 2020-12-29 07:56
So, it seems to me that the problem is on a server level. @JulioPradera the fact that you are seeing 503 page or even 404 page talks to me that your server is not configured properly. If everything is set up correctly you should see your html no matter what the URL is. Or in other words your server should return only status code 200. The idea of Navigo is to shift the routing completely to the client.

Navigo just got rewritten and I'm trying to clean up issues that are not connected to the newest version 8.0.0. This is because version 8.0.0+ is the only one that I'll support. Sorry. So I'll close this issue and let me know if you still need help.

P.S.
Version 8.0.0 is not officially released but can be installed via `npm install navigo@beta` or `yarn add navigo@beta`. Migration guide is available here https://github.com/krasimir/navigo/blob/big-rewrite/CHANGELOG.md#migration-guide and the new documentation here https://github.com/krasimir/navigo/blob/big-rewrite/DOCUMENTATION.md.

**Closed by krasimir** 2020-12-29 07:56 UTC
