### ISSUE TITLE
Regex url inconsistant

### ISSUE THREAD

**Issue by xf-** [krasimir/navigo#118] opened 2017-04-22 22:27 UTC
I use hash router and passes sometimes /# to regex if no rout is set on initialization/resolve.

If i open `domain/`
it shouldn't hit the router and match wildcard and add standard arguments. Works perfect and new url is domain/#/en/map . I click on a link and nothing happens. It passes /#/en/map to match function.

If i open with router `domain/#/en/map`
The match works great and router.on passes /en/map and everything works

My work around is a optional \/?#?

Complete regex:
on(/^\/?#?\/([\w]{2})?\/?(map|graph)?\/?([a-f\d]{12})?([a-f\d\-]{25})?\/?(?:(\d+)\/([\d.]+)\/([\d.]+))?$/, customRoute)

is this behavior intentional?

**Comment by krasimir** [comment] 2017-04-28 20:18
Just to clarify. You are at a route `domain/#/en/map` (i.e. in the address bar of the browser you see `domain/#/en/map`. Then you click a link and Navigo is not resolving your new route. If that's the case:
* What kind of a link is this. Does it contain `data-navigo` attribute?
* Did Navigo changed the URL in the address bar after the click?

**Comment by xf-** [comment] 2017-05-06 23:40
First case:
I open / and will be directed to /#/en/map (keep URL consistent with current view)

Second Case:
I open or send the current URL to somebody like` /#/fr/map/xzyxzy` or `/#/en/map`.

I don't use `data-navigo`. Most cases i use onclick and use own generate or navigo generate function.

The issue:
It looks like if hash is included opened UR, i will get a different string in regex then i click on a link.

**Comment by krasimir** [comment] 2017-05-15 15:17
I see. I'll investigate.

**Comment by krasimir** [comment] 2017-05-20 13:53
Hey @xf-, sorry for the big delay. I'm not able to reproduce your cases. I created a simple page which handles routes like `/#/en/map`. Then I put two links: one that uses `data-navigo` and one that if clicked calls Navigo's `navigate` method. In both cases the resolving works. Also the router works if I just visit those pages directly. Can you come with a page and steps where I can see the bug.

**Closed** 2017-10-07 06:06 UTC
