### ISSUE TITLE
'Before' hooks being triggered after browser navigation?

### ISSUE THREAD

**Issue by finppp** [krasimir/navigo#89] opened 2017-03-22 17:16 UTC
I am using hooks to write a new `document.title` before navigation, this allows chromes history to display the a different title making your history easier to read.

Using the before  hooks works great when using .navigate ,however when you press back on the browser a new entry is added to history but with the previous title. It seems to update your history before the hook to change the title is called. 

```
 .on(
    '/search',
    function () {
      console.log("search");
      navSearchPage()
    },
    {
      before: function (done) {
        console.log("before search");
        document.title = "MyBoathouse | Search";
        done();
      }
    }
  )
 .on(
    '/home',
    function () {
      console.log("home");
      navHomePage()
    },
    {
      before: function (done) {
        console.log("before home");
        document.title = "MyBoathouse | Home";
        done();
      }
    }
  )
```

**Comment by krasimir** [comment] 2017-03-29 19:44
Hey @finppp, I tried reproducing your problem with a unit test. Unfortunately I guess because of the click-back-button factor the test is aways passing. Did you manage to solve your problem in some way?

**Comment by finppp** [comment] 2017-03-29 20:39
Unfortunately I have not solved this. I looked into using an 'on popstate' listener and triggering a window.history.replaceState() once the title had been replaced, however this does not work.
It seems that the history api replaceState doesn't not work well with title updates. I Believe that History.js may be able to help the replaceState, however I will need to work out how to integrate this with Navigo.

Its not too important at the moment, but will look into it at some point. Unless you can think of any workarounds?

Thanks very much

**Comment by krasimir** [comment] 2017-05-28 13:55
Sorry @finppp I wasn't able to reproduce it. I'll close it for now. I really want to help but without a clear failing test I can't solve it.

**Closed by krasimir** 2017-05-28 13:55 UTC
